---
title: "App Shiny Basketball"
author: "Arshak Mkhoyan"
date: "12/2/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(stringr)
library(tidyr)
library(shiny)
library(rsconnect)
```

```{r}
load("~/Desktop/Data science/R/Sports Analitics/Project Basketball/bxsum2.rda")
end_period=data_frame()
for (i in 1:14597){
ss <- bxsum2[[i]]$resultSets$rowSet[[6]]
colnames(ss) <- bxsum2[[i]]$resultSets$headers[[6]]
#creating cumulative point
points=t(ss[,9:12])
colnames(points)=c('Home.Points', 'Away.Points')
points=as.data.frame(points)
points[,1]=as.numeric(as.character(points[,1]))
points[,2]=as.numeric(as.character(points[,2]))
for (k in 4:2){
  for (z in 1:2){
    points[k,z]=sum(points[1:k,z])
  }
}
points$Period=c(1:4)
#Add game id
game_id=data_frame(game.id=rep(as.character(ss[,3]), times=2))
#Teams names
team_names=data_frame(home=rep(as.character(ss[1,5]), times=4),away=rep(as.character(ss[2,5]), times=4))
#Year added
year_game=data.frame(year=rep(ss[1,1]%>%ymd_hms()%>%year(), times=4))
#binding all frames
full_data=bind_cols(game_id,year_game, team_names, points)
end_period=bind_rows(end_period,full_data)
}
end_period=mutate(end_period, Diff.Points=abs(Away.Points-Home.Points))%>%
  select(game.id:away, Period, Home.Points:Diff.Points)%>%
  mutate(result=ifelse(Home.Points>Away.Points,'home',ifelse(Away.Points>Home.Points,'away','draw')))

```

```{r}
end_period_noDraws_id=end_period%>%filter(Period==4, result=='draw')%>%select(game.id)
  end_period_noDraws=anti_join(end_period, end_period_noDraws_id, by='game.id')
  
find_prob1=function (dif, period, team){
game_id1=end_period_noDraws%>%
  filter(Period==period, Diff.Points==dif)%>%
    select(game.id)
first_period10=end_period_noDraws%>%
  filter(Period==period, Diff.Points==dif)%>%
  select(result)
last_period10=semi_join(end_period_noDraws, game_id1, by='game.id')%>%
  filter(Period==4)%>%
  select(result)
result_table10=as.matrix(table(first_period10$result,last_period10$result))
prob_total=(result_table10['away','away']+result_table10['home','home'])/sum(result_table10)
prob_home=result_table10['home','home']/sum(first_period10$result=='home')
prob_away=result_table10['away','away']/sum(first_period10$result=='away')
if (tolower(team)=='home') {
  prob_home
} else {
  prob_away
}
}
```

```{r}
df_prob1=data.frame(period=c(1:120), difference=c(1:120), team=c(1:120), probability=c(1:120))
for (i in 1:3){
  for (k in 1:20){
    for(ha in c('home', 'away')){
      tm=ha=='home'
    df_prob1$period[(i-1)*40+2*k-tm]=i
    df_prob1$difference[(i-1)*40+2*k-tm]=k
    df_prob1$team[(i-1)*40+2*k-tm]=ha
    df_prob1$probability[(i-1)*40+2*k-tm]=find_prob1(k, i,ha)
    }
  }
}
```

```{r}
ui <- fluidPage(
    titlePanel("Probability Computation"),
    sidebarLayout(
        sidebarPanel(
            selectInput(inputId = "team1",
                        label = "Winning team:",
                        choices = c("home", 'away')),
            
            selectInput(inputId = "period1",
                        label = "Period:",
                        choices = c("1", '2','3')),
        
            sliderInput(inputId = "Diff",
                        label = "Difference",
                        min = 1,
                        max = 20,
                        value = 5)
        ),
      
        mainPanel(
            tableOutput("values"),
            plotOutput("BarPlot"),
            plotOutput("ScatterPlot")  
            
        )
    )
)

server <- function(input, output) {
    
    sliderValues <- reactive({
        data.frame(
           Attribute= c("Team","Period","Difference","Probability"),
            Value=as.character(c(input$team1,input$period1, input$Diff,
            round(df_prob1%>%filter(period==as.numeric(input$period1), difference==as.numeric(input$Diff), team==input$team1)%>%select(probability), 3))),
            stringsAsFactors = FALSE)
        
    })
    
    output$values <- renderTable({
        sliderValues()
    })
    output$BarPlot <- renderPlot({
        game_id2=end_period_noDraws%>%
            filter(Period==as.numeric(input$period1), Diff.Points==as.numeric(input$Diff))%>%
            select(game.id)
        first_period12=end_period_noDraws%>%
            filter(Period==as.numeric(input$period1), Diff.Points==as.numeric(input$Diff))%>%
            select(result)
        last_period12=semi_join(end_period_noDraws, game_id2, by='game.id')%>%
            filter(Period==4)%>%
            select(result)
        result_table11=as.matrix(table(first_period12$result,last_period12$result))
        frame_=filter(as.data.frame(result_table11), Var1==input$team1)%>%select(Var2, Freq)
        ggplot(frame_, aes(x=Var2, y=Freq))+geom_col()+geom_text(aes(label=Freq), vjust=0)+xlab('Winning Team')+ylab('Number of Games')+ggtitle('Outcomes of games for given parameters')
    })
    output$ScatterPlot <- renderPlot({
      df_prob1%>%filter(period==as.numeric(input$period1), team==input$team1)%>%
      ggplot(aes(difference, probability))+ geom_point()+geom_line()+geom_vline(xintercept = as.numeric(input$Diff), linetype="dashed", color = "red")+geom_hline(yintercept =as.numeric(df_prob1%>%filter(period==as.numeric(input$period1), difference==as.numeric(input$Diff), team==input$team1)%>%select(probability)), linetype="dashed", color = "red")+ggtitle('Probability distribution for the given Winning team and Period')

    })
}

shinyApp(ui, server)
```

